apiVersion: v1
kind: Pod
metadata:
  name: guestbook-pod
spec:
  restartPolicy: Always
  containers:
    - name: guestbook-db
      image: postgres:16
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_DB
          value: "guestbook"
        - name: POSTGRES_USER
          value: "gb-user"
        - name: POSTGRES_PASSWORD
          value: "gb-pass"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: guestbook-dbdata
          mountPath: /var/lib/postgresql/data
        - name: resources
          mountPath: /docker-entrypoint-initdb.d/
      # Podman-specific note: To set shared memory size, run Podman with --shm-size=256mb if needed.
    
    # - name: guestbook-app
    #   image: gb
    #   imagePullPolicy: Never
    #   ports:
    #     - containerPort: 9090
    #       hostPort: 9090
  
  volumes:
    - name: guestbook-dbdata
      hostPath:
        # Adjust this host path to point to your external volume directory.
        path: /var/lib/guestbook-dbdata
    - name: resources
      hostPath:
        # Path to your SQL file (guestbook-ddl.sql renamed as init.sql)
        path: ../resources/
