version: '3.3'
services:
  app:
    container_name: shorten-url-app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"